name: Auto approval for backmerge

on:
  pull_request:
    types: [opened, reopened, labeled, edited]
  pull_request_review:
    types: [dismissed]
    
permissions:
  contents: read
  pull-requests: write
  
jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Autoapproval
    if: |
      (github.event.pull_request.head.ref == 'main' && github.event.pull_request.base.ref == 'qs') ||
      (github.event.pull_request.head.ref == 'qs' && github.event.pull_request.base.ref == 'dev')
    steps:
      - uses: dkhmelenko/autoapproval@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
